### ISSUE TITLE
Rajapinnat alhaalla?

### ISSUE THREAD

**Issue by ToniIltanen** [6aika/api-paatos#13]
Onko https://paatos-helsinki.6aika.fi alhaalla?

**Comment by aapris** [comment]
Uusi osoite on https://api.hel.fi/paatos/v1/

Valitettavasti muiden kaupunkien rajapinnat ovat toistaiseksi alhaalla eikä niiden jatkumisesta ole mitään varmaa tietoa. Joka tapauksessa paatos-*.6aika.fi apit ovat poissa, koska projekti on päättynyt.
