### ISSUE TITLE
Swagger vs actual API

### ISSUE THREAD

**Issue by ToniIltanen** [6aika/api-paatos#3]
It seems that the implementation of your API (paatos-helsinki.6aika.fi/v1/) does not match the swagger according to the Django Rest Framework
Only supported endpoints are:

Endpoint | url
---------| ----
action | https://paatos-helsinki.6aika.fi/v1/case
function | https://paatos-helsinki.6aika.fi/v1/function
event | https://paatos-helsinki.6aika.fi/v1/event
organization | https://paatos-helsinki.6aika.fi/v1/organization
post | https://paatos-helsinki.6aika.fi/v1/post

Is there a timeline, when the rest of the swagger schema is applied to the working API?

**Comment by aapris** [comment]
Swagger and API will be sync'ed in autumn 2017 (Sep-Oct I guess) when there will be next time some work on progress.

**Comment by ToniIltanen** [comment]
Will it be V2 or still V1 of the rest API? In other terms, does the current online V1 version API's (Oulu, Turku, Helsinki, Vantaa, Espoo, Tampere) keep the current endpoints as they are, or will they change also? When versioning API's they should not change, instead a new version should be launched so current applications using the api will not break

**Comment by aapris** [comment]
Backward incompatible changes will mean v2. Probably something will change, so it will be v2 then. 

BTW, it seems all päätös-APIs will move to some other server in the end of 2017 (this project ends), so prepare to update yours apps. The new address may be something like api.cityname.fi/decisions/v2/ .
